parameters:

services:
    slim:
        class:     'Slim\Slim'
        calls:
            - [registerAutoloader, []]
    build:
        class:     'Opine\Build'
        arguments: ['@pubSubBuild', '@collectionRoute', '@helperRoute', '@formRoute', '@configRoute', '@bundleRoute', '@fieldRoute', '@filter', '@cache', '@search', '@authentication']
    pubSubBuild:
        class:     'Opine\PubSubBuild'
        arguments: ['%root%', '@yamlSlow']
    topic:
        class:     'Opine\Topic'
        arguments: ['@container']
    separation:
        class:     'Opine\Separation'
        arguments: ['%root%', '@handlebars', '@cache', '@config', '@yamlSlow', '@slim']
    collectionRoute:
        class:     'Opine\CollectionRoute'
        arguments: ['@collection', '@slim', '@db', '@separation', '@response']
    collection:
        class:     'Opine\Collection'
        arguments: ['%root%', '@db', '@queue']
    field:
        class:     'Opine\Field'
        arguments: ['%root%', '@db', '@manager']
    fieldRoute:
        class:     'Opine\FieldRoute'
    captcha:
        class:     'Captcha\Captcha'
    formRoute:
        class:     'Opine\FormRoute'
        arguments: ['@slim', '@form', '@field', '@post', '@separation', '@topic', '@response']
    form:
        class:     'Opine\Form'
        arguments: ['%root%', '@field', '@post', '@db', '@response']
    managerRoute:
        class:     'Opine\ManagerRoute'
        arguments: ['@authentication', '@separation', '@slim', '@form', '@manager']
    manager:
        class:     'Opine\Manager'
        arguments: []
    authentication:
        class:     'Opine\Authentication'
        arguments: ['%root%', '@db', '@config', '@yamlSlow', '@slim', '@cache']
    helperRoute:
        class:     'Opine\HelperRoute'
        arguments: ['@slim', '@handlebars']
    configRoute:
        class:     'Opine\ConfigRoute'
        arguments: ['@config', '@cache']
    filter:
        class:     'Opine\Filter'
        arguments: ['@response']
    cache:
        class:     'Opine\Cache'
    handlebars:
        class:     'Handlebars\Handlebars'
    config:
        class:     'Opine\Config'
        arguments: ['%root%', '@cache']
    db:
        class:     'Opine\Mongo'
        arguments: ['@config', '@topic']
    dbmigration:
        class:     'Opine\Migration'
        arguments: ['@db']
    post:
        class:     'Opine\HTTPPost'
    response:
        class:     'Opine\HTTPResponse'
    person:
        class:     'Opine\Person'
        arguments: ['@db', '@config']
    errors:
        class:     'Opine\Errors'
        arguments: ['@config', '@topic', '@separation']
    mail:
        class:     'Opine\Mail'
        arguments: ['@mailSES']
    mailSES:
        class:     'Opine\SES'
        arguments: ['@config']
    yamlSlow:
        class:     'Symfony\Component\Yaml\Yaml'
    queueGateway: 
        class:     'Pheanstalk_Pheanstalk'
        arguments: ['127.0.0.1']
    queue:
        class:     'Opine\Queue'
        arguments: ['@queueGateway', '%root%']
    worker:
        class:     'Opine\Worker'
        arguments: ['@queueGateway', '@topic', '%root%']
    searchGateway:
        class:     'Elasticsearch\Client'
    search:
        class:     'Opine\Search'
        arguments: ['@searchGateway', '%root%']
    bundleRoute:
        class:     'Opine\BundleRoute'
        arguments: ['@container']
    manager:
        class:     'Opine\Manager'
        arguments: ['@separation', '@response', '%root%']
    uploadwrapper:
        class:     'Opine\UploadWrapper'
        arguments: ['%root%']
    slugify:
        class:     'Cocur\Slugify\Slugify'
    imageResizer:
        class:     'Opine\ImageResizer'
        arguments: ['@slim']
    twitter:
        class:     'Opine\Twitter'
        arguments: ['%root%', '@cache', '@queue', '@db', '@config']