parameters:

services:
    route:
        class:     'Opine\Route'
        arguments: ['@fastrouteCollector']
    fastrouteCollector:
        class:     'FastRoute\RouteCollector'
        arguments: ['@fastrouteParser', '@fastrouteGenerator']
    fastrouteParser:
        class:     'FastRoute\RouteParser\Std'
    fastrouteGenerator:
        class:     'FastRoute\DataGenerator\GroupCountBased'
    build:
        class:     'Opine\Build'
        arguments: ['@pubSubBuild', '@collectionRoute', '@helperRoute', '@formRoute', '@configRoute', '@bundleRoute', '@fieldRoute', '@filter', '@cache', '@search', '@authentication']
    pubSubBuild:
        class:     'Opine\PubSubBuild'
        arguments: ['%root%', '@yamlSlow']
    topic:
        class:     'Opine\Topic'
        arguments: ['@container']
    separation:
        class:     'Opine\Separation'
        arguments: ['%root%', '@handlebars', '@cache', '@config', '@yamlSlow', '@route']
    collectionRoute:
        class:     'Opine\CollectionRoute'
        arguments: ['%root%', '@collection', '@route', '@db', '@separation']
    collection:
        class:     'Opine\Collection'
        arguments: ['%root%', '@db', '@queue']
    field:
        class:     'Opine\Field'
        arguments: ['%root%', '@container']
    fieldRoute:
        class:     'Opine\FieldRoute'
    captcha:
        class:     'Captcha\Captcha'
    formRoute:
        class:     'Opine\FormRoute'
        arguments: ['@route', '@form', '@field', '@post', '@separation', '@topic', '%root%']
    form:
        class:     'Opine\Form'
        arguments: ['%root%', '@field', '@post', '@db', '@separation']
    authentication:
        class:     'Opine\Authentication'
        arguments: ['%root%', '@db', '@config', '@yamlSlow', '@route', '@cache']
    helperRoute:
        class:     'Opine\HelperRoute'
        arguments: ['@route', '@handlebars']
    configRoute:
        class:     'Opine\ConfigRoute'
        arguments: ['@config', '@cache']
    filter:
        class:     'Opine\Filter'
        arguments: []
    cache:
        class:     'Opine\Cache'
    handlebars:
        class:     'Handlebars\Handlebars'
    config:
        class:     'Opine\Config'
        arguments: ['%root%', '@cache']
    db:
        class:     'Opine\Mongo'
        arguments: ['@config', '@topic']
    dbmigration:
        class:     'Opine\Migration'
        arguments: ['@db']
    post:
        class:     'Opine\HTTPPost'
    person:
        class:     'Opine\Person'
        arguments: ['@db', '@config']
    errors:
        class:     'Opine\Errors'
        arguments: ['@config', '@topic', '@separation']
    mail:
        class:     'Opine\Mail'
        arguments: ['@mailSES']
    mailSES:
        class:     'Opine\SES'
        arguments: ['@config']
    yamlSlow:
        class:     'Symfony\Component\Yaml\Yaml'
    queueGateway: 
        class:     'Pheanstalk_Pheanstalk'
        arguments: ['127.0.0.1']
    queue:
        class:     'Opine\Queue'
        arguments: ['@queueGateway', '%root%']
    worker:
        class:     'Opine\Worker'
        arguments: ['@queueGateway', '@topic', '%root%']
    searchGateway:
        class:     'Elasticsearch\Client'
    search:
        class:     'Opine\Search'
        arguments: ['@searchGateway', '%root%']
    bundleRoute:
        class:     'Opine\BundleRoute'
        arguments: ['@container', '%root%']
    manager:
        class:     'Opine\Manager\Manager'
        arguments: ['@separation', '%root%']
    uploadwrapper:
        class:     'Opine\UploadWrapper'
        arguments: ['%root%']
    slugify:
        class:     'Cocur\Slugify\Slugify'
    imageResizer:
        class:     'Opine\ImageResizer'
        arguments: ['@route']
    twitter:
        class:     'Opine\Twitter'
        arguments: ['%root%', '@cache', '@queue', '@db', '@config']
    registration:
        class:     'Opine\Registration'
        arguments: ['@db']
    financial:
        class:     'Opine\Financial'
        arguments: ['@db', '@creditcardgateway', '@cashgateway', '@checkgateway', '@storecreditgateway', '@giftcardgateway']